DATABASE_SCHEMA = """
Database: quantumedge_corporation

TABLE: regions
- REGION_ID INT PRIMARY KEY
- REGION_NAME VARCHAR(100)

TABLE: countries
- COUNTRY_ID CHAR(2) PRIMARY KEY
- COUNTRY_NAME VARCHAR(100)
- REGION_ID INT
  FOREIGN KEY → regions.REGION_ID

TABLE: locations
- LOCATION_ID INT PRIMARY KEY
- STREET_ADDRESS VARCHAR(255)
- POSTAL_CODE VARCHAR(20)
- CITY VARCHAR(100)
- STATE_PROVINCE VARCHAR(100)
- COUNTRY_ID CHAR(2)
  FOREIGN KEY → countries.COUNTRY_ID

TABLE: departments
- department_id INT PRIMARY KEY
- department_name VARCHAR(50)
- manager_id INT
  FOREIGN KEY → employees.EMPLOYEE_ID
- location_id INT
  FOREIGN KEY → locations.LOCATION_ID

TABLE: jobs
- JOB_ID VARCHAR(20) PRIMARY KEY
- job_title VARCHAR(100)
- MIN_SALARY DECIMAL(10,2)
- MAX_SALARY DECIMAL(10,2)

TABLE: employees
- EMPLOYEE_ID INT PRIMARY KEY
- FIRST_NAME VARCHAR(20)
- LAST_NAME VARCHAR(25)
- email VARCHAR(50)
- PHONE_NUMBER VARCHAR(20)
- HIRE_DATE DATE
- JOB_ID VARCHAR(10)
  FOREIGN KEY → jobs.JOB_ID
- SALARY DECIMAL(8,2)
- COMMISSION_PCT DECIMAL(2,2)
- MANAGER_ID INT
  FOREIGN KEY → employees.EMPLOYEE_ID
- DEPARTMENT_ID INT
  FOREIGN KEY → departments.department_id

TABLE: job_history
- EMPLOYEE_ID INT
  FOREIGN KEY → employees.EMPLOYEE_ID
- START_DATE DATE
- END_DATE DATE
- JOB_ID VARCHAR(20)
  FOREIGN KEY → jobs.JOB_ID
- DEPARTMENT_ID INT
  FOREIGN KEY → departments.department_id

RELATIONSHIPS:
- countries.REGION_ID → regions.REGION_ID
- locations.COUNTRY_ID → countries.COUNTRY_ID
- departments.LOCATION_ID → locations.LOCATION_ID
- departments.MANAGER_ID → employees.EMPLOYEE_ID
- employees.JOB_ID → jobs.JOB_ID
- employees.DEPARTMENT_ID → departments.department_id
- employees.MANAGER_ID → employees.EMPLOYEE_ID
- job_history.EMPLOYEE_ID → employees.EMPLOYEE_ID
- job_history.JOB_ID → jobs.JOB_ID
- job_history.DEPARTMENT_ID → departments.department_id
"""
